```javascript
// HARDCORE-SET (CREATIVE & DIVERSE): 100 Aufgaben für ein 12-Stunden-Bingo.
// difficulty: 1 = grün (1 Pt / Hardcore), 2 = orange (2 Pts / Brutal), 3 = rot (3 Pts / Extrem).
// Fokus: Klare Namen (Englisch), Parkour, Sammeln, Combat-Mechaniken, Boss-Restriktionen & World Exploration.

export const TASKS = [
  // --- GRÜN: HARDCORE (35 Aufgaben - je 1 Punkt) ---
  {t:"Erreiche Roundtable Hold, ohne an einer Grace in Limgrave zu restenn.",d:1},
  {t:"Besiege Margit nur mit Daggern (kein Bleed/Poison/Rot-Proc).",d:1},
  {t:"Besiege Tree Sentinel in Limgrave zu Fuß, ohne Summons & ohne Ranged Damage.",d:1},
  {t:"Besiege Bloodhound Knight Darriwil ohne Blaidd, Shield oder Red Flasks.",d:1},
  {t:"Töte 10 verschiedene Schildkröten (Dog) mit Nahkampf.",d:1},
  {t:"Aktiviere den Divine Tower of Limgrave komplett nackt.",d:1},
  {t:"Kaufe ALLE Items bei 3 verschiedenen Merchanten leer.",d:1},
  {t:"Meistere den Parkour unter Stormveil Castle zum Ulcerated Tree Spirit ohne Death.",d:1},
  {t:"Finde 5 verschiedene Perfume Bottles.",d:1},
  {t:"Besiege 3 NPC-Invasoren (z.B. Nerijus, Anastasia, Okina) nur mit Fists / Unarmed.",d:1},
  {t:"Sammle 5 verschiedene Whetblades.",d:1},
  {t:"Reite auf Torrent vom First Step bis Raya Lucaria Academy, ohne 1x abzusteigen.",d:1},
  {t:"Sammle mindestens 12 verschiedene Emotes.",d:1},
  {t:"Stelle 20 Pots her und wirf alle 20 erfolgreich auf einen Boss, um ihn zu finishen.",d:1},
  {t:"Löse das Turm-Rätsel in Oridys's Tower und Testu's Tower.",d:1},
  {t:"Sammle 6 verschiedene Paintings (Gemälde).",d:1},
  {t:"Sammle 15 verschiedene Spirit Ashes, ohne eine einzige aufzuwerten.",d:1},
  {t:"Absolviere Castle Morne inklusive Boss, ohne ein Shield zu benutzen.",d:1},
  {t:"Besiege Pumpkin Head in Waypoint Ruins, ohne seinen Kopf-Helm zu treffen.",d:1},
  {t:"Zerstöre 1 Chariot in einem Hero's Grave durch Fallen/Mechaniken.",d:1},
  {t:"Lerne 15 verschiedene Incantations oder Sorceries.",d:1},
  {t:"Besiege einen Boss ausschließlich mit Guard Counters und Critical Hits.",d:1},
  {t:"Besiege einen Boss nur mit Torch (Fackel) als Schadensquelle.",d:3},
  {t:"Besiege einen Boss nur mit Bow / Crossbow (keine Status-Pfeile, keine Summons).",d:1},
  {t:"Besiege einen Boss ohne Rollen, Springen oder Sprinten.",d:3},
  {t:"Besiege einen Boss nackt (keine Armor), ohne Summons und ohne Red Flasks.",d:2},
  {t:"Besiege einen Boss, während du Heavy Load (Schwer beladen) bist; ohne Shield.",d:2},
  {t:"Besiege einen Boss mit max. 10% HP zu Kampfbeginn und heile während des Kampfes nicht.",d:3},
  {t:"Besiege zwei verschiedene Bosse hintereinander, ohne dazwischen an einer Grace zu restenn.",d:1},
  {t:"Besiege 3 verschiedene Evergaol-Bosse ohne Summons und ohne dazwischen zu sterben.",d:2},
  {t:"Töte den schlafenden Riesendrachen Greyoll ohne Bleed-Waffe.",d:1},
  {t:"Sammle 5 verschiedene Bell Bearings und gib sie bei Twin Maiden Husks ab.",d:1},
  {t:"Finde und öffne 6 verschiedene Stonesword-Key-Siegel in 4 Regionen.",d:1},
  {t:"Erreiche Altus Plateau, ohne den Grand Lift of Dectus zu benutzen.",d:1},
  {t:"Durchquere Cave of Knowledge / Tutorial nackt und ohne Healing Items.",d:1},

  // --- ORANGE: BRUTAL (40 Aufgaben - je 2 Punkte) ---
  {t:"Überlebe Auriza Hero's Grave ohne Armor, ohne Rasten & besiege das Crucible Knight Duo.",d:2},
  {t:"Erreiche Frenzied Flame Proscription unter Leyndell, OHNE beim Parkour zu sterben.",d:2},
  {t:"Sammle ALLE 9 Legendary Armaments (Waffen) im Spiel.",d:2},
  {t:"Sammle ALLE 8 Legendary Talismans im Spiel.",d:2},
  {t:"Sammle ALLE 7 Legendary Sorceries & Incantations.",d:2},
  {t:"Durchquere Lake of Rot zu Fuß OHNE Preserving Boluses oder 'Flame, Cleanse Me'.",d:2},
  {t:"Besiege Astel, Naturalborn of the Void nur mit Gravity Magic / Schwerkaft-Sachen.",d:2},
  {t:"Infiltriere Leyndell über Deeproot Depths (Fia Teleporter), ohne Dectus/Makar zu nutzen.",d:2},
  {t:"Töte 3 Drachen in 3 verschiedenen Regionen innerhalb von 30 Minuten Spielzeit.",d:2},
  {t:"Bringe eine Somber-Waffe auf +10, BEVOR du Mountaintops of the Giants betrittst.",d:2},
  {t:"Sammle 500.000 Runen auf einmal, ohne sie auszugeben oder Sacrificial Twigs zu nutzen.",d:2},
  {t:"Durchquere die Haligbaum-Baumkronen (Haligtree Canopy) bis zur Stadt, ohne abzustürzen.",d:2},
  {t:"Finde und aktiviere 60 verschiedene Graces auf der Karte.",d:2},
  {t:"Besiege Rykard Phase 2 OHNE Ash of War / Skill des Serpent-Hunters zu nutzen.",d:2},
  {t:"Töte Alecto, Black Knife Ringleader nur mit Parries / Ripostes.",d:2},
  {t:"Erreiche Deeproot Depths über die Frenzied Flame Illusion Wall.",d:2},
  {t:"Besiege 5 verschiedene Night's Cavalry ausschließlich in der Nacht.",d:2},
  {t:"Verursache an 5 verschiedenen Bossen den Last Hit mit einem Throwing Pot.",d:2},
  {t:"Besiege Ancestor Spirit, ohne ein einziges Mal zu dodgen (Rollen) oder zu springen.",d:2},
  {t:"Besiege Rennala Phase 2, ohne dass sie ein einziges Phantom/Summon beschwört.",d:2},
  {t:"Stelle deine Ausrüstung auf exakt 100% Carry Weight (Overloaded) & töte einen Field Boss.",d:2},
  {t:"Besiege Radahn ohne NPC- oder Player-Summons, Torrent oder Red Flasks.",d:3},
  {t:"Besiege Valiant Gargoyles ohne Summons und ohne Poison/Rot Cheese.",d:2},
  {t:"Besiege Godskin Apostle im Divine Tower of Caelid ohne Sleep, Summons oder Red Flasks.",d:2},
  {t:"Besiege Bell Bearing Hunter in Dragonbarrow ohne Summons & Ranged Damage.",d:2},
  {t:"Besiege Putrid Avatar in Dragonbarrow ohne Torrent, Summons oder Ranged Damage.",d:2},
  {t:"Besiege Black Blade Kindred vor Bestial Sanctum ohne Summons oder Ranged Damage.",d:2},
  {t:"Sammle 12 Sacred Tears und upgrade deine Flask auf +12.",d:2},
  {t:"Maximiere deine Flask Charges auf 14.",d:2},
  {t:"Sammle je eine Smithing Stone Stufe 1 bis 8 & Somber Stone Stufe 1 bis 9 im Inventar.",d:2},
  {t:"Bringe eine normale Waffe auf +25 und eine Somber-Waffe auf +10.",d:2},
  {t:"Besiege Mimiq Tear in Nokron, während du voll ausgerüstet die Arena betrittst (nichts unequipen!).",d:2},
  {t:"Besiege Full-Grown Fallingstar Beast auf Mt. Gelmir ohne Torrent/Summons.",d:2},
  {t:"Aktiviere 4 verschiedene Great Runes an ihren Göttlichen Türmen.",d:2},
  {t:"Besiege Morgott ohne Summons/Melina, Shield und ohne Red Flasks.",d:2},
  {t:"Besiege Mohg, Lord of Blood ohne Summons und ohne Mohg's Shackle.",d:2},
  {t:"Besiege Maliketh, the Black Blade ohne Summons.",d:2},
  {t:"Besiege Dragonlord Placidusax ohne Summons.",d:2},
  {t:"Besiege Godfrey / Hoarah Loux ohne Summons und ohne Red Flasks.",d:2},
  {t:"Besiege Radagon & Elden Beast ohne Summons.",d:2},

  // --- ROT: WAHNSINN / EXTREM (35 Aufgaben - je 3 Punkte) ---
  {t:"Absolviere das Spiel komplett OHNE die Ingame-Map ein einziges Mal zu öffnen.",d:3},
  {t:"Besiege Malenia im Fingerprint Armor Set, OHNE Shield, Bleed oder Summons.",d:3},
  {t:"Besiege Godskin Duo, indem du BEIDE Bosse innerhalb von 10 Sek. Abstand tötest.",d:3},
  {t:"Durchquere Farum Azula von der ersten Grace bis Maliketh ohne Resten & ohne Death.",d:3},
  {t:"Besiege Malenia, Blade of Miquella komplett nackt und nur mit einer +0 Club (Keule).",d:3},
  {t:"Erreiche Elphael (Prayer Room Grace), ohne ab Haligbaum-Start 1 Gegner zu töten.",d:3},
  {t:"Besiege Maliketh ausschließlich unter Nutzung des Blasphemous Claw Parries.",d:3},
  {t:"Sammle 2.000.000 Runen gleichzeitig auf dem Konto und besiege damit Fire Giant.",d:3},
  {t:"Besiege Placidusax nackt und ohne Flask of Wondrous Physick.",d:3},
  {t:"Reise von Limgrave bis Consecrated Snowfield OHNE 1x Fast Travel zu nutzen.",d:3},
  {t:"Besiege Commander Niall in Castle Sol, ohne seine 2 Banished Knights zu töten.",d:3},
  {t:"Besiege Mohg, Lord of Blood, BEVOR er Phase 2 ('Nihil!') einleiten kann.",d:3},
  {t:"Erreiche Level 120 ausschließlich durch Boss-Kills (Kein Farmen an Albinaurics!).",d:3},
  {t:"Besiege Radagon & Elden Beast direkt nacheinander mit max. 4 Red Flasks gesamt.",d:3},
  {t:"Besiege Lichdragon Fortissax innerhalb von 90 Sekunden ab Arenabetritt.",d:3},
  {t:"Durchquere Subterranean Shunning-Grounds inklusive Mohg the Omen ohne Fackel/Lantern.",d:3},
  {t:"Besiege Godfrey / Hoarah Loux nur mit Bare Fists / Caestus.",d:3},
  {t:"Besiege 10 verschiedene benannte Drachen im gesamten Spiel.",d:3},
  {t:"Besiege Bell Bearing Hunter in Dragonbarrow nackt nur mit Shield-Bashing.",d:3},
  {t:"Töte Malenia Phase 2 mit einem Throwing Pot als Todesstoß.",d:3},
  {t:"Besiege 4 verschiedene Death Rite Birds in der Nacht.",d:3},
  {t:"Besiege Radahn ohne Torrent, ohne Summons, nackt und mit max. 10% HP zu Beginn.",d:3},
  {t:"Besiege alle 3 Magma Wyrms im Spiel (Makar, Mt. Gelmir, Gael Tunnel).",d:3},
  {t:"Besiege Putrid Tree Spirit im War-Dead Catacombs (Radahn Arena) ohne Armor.",d:3},
  {t:"Absolviere Volcano Manor komplett ohne die Fahrstuhl-/Shortcut-Abkürzungen.",d:3},
  {t:"Töte Elden Beast mit einer Holy Damage Waffe / Holy Art.",d:3},
  {t:"Trage während des gesamten 12h Runs den Baldachin's Blessing (5% HP-Debuff von Fia).",d:3},
  {t:"Besiege 5 verschiedene Ulcerated Tree Spirits.",d:3},
  {t:"Sammle 100 verschiedene Rüstungsteile (Armor Pieces) im Inventar.",d:3},
  {t:"Löse in EINEM Bossversuch Bleed, Frost und Poison/Rot am selben Boss aus und gewinne.",d:3},
  {t:"Durchquere Sellia Crystal Tunnel von der Grace bis Boss & töte Fallingstar Beast ohne Death/Rest.",d:3},
  {t:"Besiege Fire Giant ohne Torrent, Summons oder Red Flasks.",d:3},
  {t:"Besiege Death Rite Bird im Consecrated Snowfield ohne Holy Damage, Summons oder Ranged.",d:3},
  {t:"Besiege Elemer of the Briar ohne Summons, Shield oder Red Flasks.",d:3},
  {t:"Besiege 5 verschiedene Bosse in 5 verschiedenen Regionen innerhalb von 60 Min. ohne Summons.",d:3}
];

```