// difficulty: 1 = grün / 1 Punkt, 2 = orange / 2 Punkte, 3 = rot / 3 Punkte
export const TASKS = [
  {t:"Besiege Margit, das Grausame Mal, ohne Geisterasche.",d:1},
  {t:"Aktiviere drei verschiedene Orte der Gnade in Caelid, ohne unterwegs einen Boss zu töten.",d:1},
  {t:"Besiege einen Nachtkavalleristen bei Nacht.",d:2},
  {t:"Sammle 3 verschiedene Heilige Tränen.",d:1},
  {t:"Töte einen Runenbären, ohne auf Torrent zu steigen.",d:2},
  {t:"Besiege Godrick und benutze während des Kampfes keine Geisterasche.",d:1},
  {t:"Erreiche den Altus-Plateau-Aufzug und aktiviere dort einen Ort der Gnade.",d:1},
  {t:"Besiege einen Erdtree-Avatar nur mit Nahkampfschaden.",d:2},
  {t:"Öffne eine Schatztruhe, die dich per Teleporterfalle an einen gefährlichen Ort transportiert, und entkomme lebend bis zu einer Gnade.",d:2},
  {t:"Besiege einen Drachen, ohne Torrent während des Kampfes zu benutzen.",d:2},
  {t:"Sammle 5 verschiedene Kochbücher.",d:1},
  {t:"Besiege einen Boss mit höchstens 3 verbleibenden Heilfläschchen-Nutzungen insgesamt im Kampf.",d:1},
  {t:"Aktiviere beide Hälften des Dectus-Medaillons.",d:1},
  {t:"Besiege Rennala.",d:1},
  {t:"Töte einen Boss, während du schwere Ausrüstungslast hast.",d:2},
  {t:"Besiege den Baumwächter direkt vor Limgrave, ohne ihn von einer Klippe oder mit Terrain auszutricksen.",d:2},
  {t:"Finde und öffne 4 verschiedene Steinschwertschlüssel-Siegel.",d:2},
  {t:"Besiege einen Kristallianer mit einer Waffe, die zu Kampfbeginn nicht mehr als +3/+1 verbessert ist.",d:2},
  {t:"Erreiche Volcano Manor und aktiviere dort eine Gnade.",d:2},
  {t:"Besiege den Roten Wolf von Radagon ohne Schild.",d:2},
  {t:"Sammle 6 verschiedene Talismane.",d:1},
  {t:"Besiege einen Boss ausschließlich mit einer Zweihand-geführten Waffe; keine Zauber, Bögen oder Schilde.",d:2},
  {t:"Erreiche Nokron, die Ewige Stadt, und aktiviere dort eine Gnade.",d:2},
  {t:"Besiege Radahn ohne andere Spieler zu beschwören.",d:2},
  {t:"Töte 3 verschiedene große Krabben oder Hummer, ohne zwischen den Kills an einer Gnade zu rasten.",d:1},
  {t:"Besiege einen Erdtree-Wachhund in einer Katakombe, ohne getroffen zu werden.",d:3},
  {t:"Finde 3 verschiedene Kartenfragmente innerhalb von 45 Minuten Spielzeit ab Claim.",d:2},
  {t:"Besiege einen Boss mit einer Fackel als einzige Schadensquelle.",d:3},
  {t:"Sammle 4 verschiedene Zaubereien oder Anrufungen, obwohl du sie nicht benutzen musst.",d:1},
  {t:"Besiege den Leoninen Bastard in Schloss Morne.",d:1},
  {t:"Töte einen Unsichtbaren Skarabäus und erhalte seine Belohnung.",d:2},
  {t:"Erhalte eine Große Rune und aktiviere sie anschließend am passenden Göttlichen Turm.",d:2},
  {t:"Besiege einen Boss, ohne während des gesamten Kampfes zu rollen.",d:3},
  {t:"Sammle 12 verschiedene Gnadenpunkte in einer einzigen Region.",d:1},
  {t:"Besiege einen Todesvogel oder Todesritenvogel.",d:2},
  {t:"Töte einen Boss mit einem kritischen Treffer als finalem Schlag.",d:2},
  {t:"Besiege einen Boss, nachdem du zu Kampfbeginn absichtlich unter 30% LP gegangen bist; heilen danach erlaubt.",d:3},
  {t:"Finde eine Larventräne.",d:1},
  {t:"Besiege den Magmalindwurm Makar.",d:2},
  {t:"Erreiche die Hauptstadt Leyndell und aktiviere eine Gnade innerhalb der Stadtmauer.",d:2},
  {t:"Besiege einen Omen-Killer.",d:2},
  {t:"Sammle 3 verschiedene Kriegsaschen und wende mindestens eine davon auf eine Waffe an.",d:1},
  {t:"Besiege einen Boss nur mit Wurfgegenständen und Verbrauchsgegenständen als Schadensquelle.",d:3},
  {t:"Töte einen riesigen Land-Oktopus und einen Runenbären innerhalb von 10 Minuten, ohne an einer Gnade zu rasten.",d:2},
  {t:"Finde eine legendäre Waffe oder einen legendären Talisman.",d:3},
  {t:"Besiege einen Black-Knife-Assassinen.",d:2},
  {t:"Erreiche Deeproot Depths und aktiviere eine Gnade.",d:3},
  {t:"Besiege Morgott.",d:2},
  {t:"Gewinne einen Bosskampf, ohne eine einzige Flasche zu benutzen.",d:3},
  {t:"Sammle 10 verschiedene Handwerksmaterialien aus Caelid und kehre danach lebend zu einer Gnade zurück.",d:1},
  {t:"Besiege einen Ulcerated Tree Spirit.",d:2},
  {t:"Töte 5 Feinde nacheinander nur mit Guard Counters, ohne dazwischen Schaden mit einer anderen Aktion zu verursachen.",d:2},
  {t:"Besiege einen Boss mit einer Waffe, deren Attribut-Anforderungen du exakt erfüllst, aber nicht überschreitest (Toleranz: +0 bei allen Anforderungen).",d:3},
  {t:"Sammle 3 verschiedene Erinnerung- oder Bossseelen-Belohnungen insgesamt.",d:2},
  {t:"Besiege einen Drachen und lande den finalen Treffer zu Fuß am Kopf.",d:2},
  {t:"Erreiche den Mohgwyn-Palast und aktiviere dort eine Gnade.",d:3},
  {t:"Besiege einen Gargoyle-Boss.",d:3},
  {t:"Finde 5 verschiedene Händler und kaufe von jedem mindestens einen Gegenstand.",d:1},
  {t:"Besiege einen Boss mit einer unverstärkten Waffe (+0), ohne offensive Magie.",d:3},
  {t:"Besiege einen Bell Bearing Hunter.",d:3},
  {t:"Töte 10 Feinde mit einer einzigen Waffe, ohne an einer Gnade zu rasten oder die Waffe zu wechseln.",d:1},
  {t:"Erreiche den Lake of Rot und aktiviere eine Gnade.",d:3},
  {t:"Besiege einen Boss mit Gift oder Scharlachfäule als finaler Schadensquelle.",d:2},
  {t:"Sammle 5 verschiedene Schilde.",d:1},
  {t:"Besiege einen Crucible Knight ohne Geisterasche.",d:3},
  {t:"Töte einen Boss, ohne die Kamera auf ihn zu locken.",d:3},
  {t:"Aktiviere 3 Große Aufzüge/Teleport-Portale/regionale Transportmechanismen unterschiedlicher Art.",d:2},
  {t:"Besiege Rykard.",d:2},
  {t:"Sammle 50.000 Runen auf einmal und gib sie anschließend aus, ohne sie vorher zu verlieren.",d:2},
  {t:"Besiege einen Boss mit weniger als 10% LP am Ende des Kampfes.",d:2},
  {t:"Töte 3 Skarabäen unterschiedlicher Art/Farbe innerhalb von 20 Minuten.",d:2},
  {t:"Besiege einen Duo-Boss ohne Geisterasche.",d:3},
  {t:"Finde 4 verschiedene Kristalltränen für die Wundersame Arznei.",d:1},
  {t:"Besiege einen Boss, während du keine Rüstungsteile trägst.",d:3},
  {t:"Erreiche das Geweihte Schneefeld und aktiviere dort eine Gnade.",d:3},
  {t:"Besiege Commander Niall.",d:3},
  {t:"Sammle 3 verschiedene Glockenlager und gib mindestens eines bei den Zwillingsjungferhüllen ab.",d:2},
  {t:"Töte einen Boss mit einer Armbrust oder einem Bogen als einziger direkter Schadensquelle.",d:3},
  {t:"Besiege einen Erdtree Burial Watchdog nur mit Sprungangriffen als direkter Schadensquelle.",d:2},
  {t:"Erhalte 2 verschiedene Gesten durch NPC-Interaktion oder Spielfortschritt.",d:1},
  {t:"Besiege Godfrey/Hoarah Loux.",d:3},
  {t:"Besiege einen Boss mit maximal 25% deiner maximalen Ausrüstungslast ausgerüstet.",d:2},
  {t:"Sammle 3 verschiedene Waffenarten (z.B. Speer, Peitsche, Großschwert) aus Schatztruhen oder festen Fundorten, nicht von Händlern.",d:1},
  {t:"Töte 6 Feinde hintereinander mit Backstabs, ohne dazwischen entdeckt und getroffen zu werden.",d:2},
  {t:"Besiege einen Avatar/Putrid Avatar ohne Torrent, Geisterasche oder Fernkampfschaden.",d:3},
  {t:"Erreiche Miquellas Haligbaum und aktiviere eine Gnade.",d:3},
  {t:"Besiege Loretta in einer ihrer Bossvarianten ohne Geisterasche.",d:2},
  {t:"Sammle 8 verschiedene Kopf-Rüstungsteile.",d:1},
  {t:"Besiege einen Boss, nachdem du im selben Versuch mindestens einmal Frost und Blutung auf ihn ausgelöst hast.",d:3},
  {t:"Töte einen Feind mit Fallschaden, den du aktiv durch einen Angriff/Stoß verursacht hast.",d:2},
  {t:"Besiege einen Boss mit einer Waffe, die du erst innerhalb der letzten 20 Minuten gefunden hast.",d:2},
  {t:"Erreiche 10 Fläschchen-Gesamtnutzungen durch Goldene Saaten.",d:1},
  {t:"Besiege Maliketh.",d:3},
  {t:"Besiege einen Boss ohne Sprinten, Rollen oder Springen im Kampf.",d:3},
  {t:"Sammle 3 verschiedene Drachenherzen.",d:2},
  {t:"Töte einen Boss ausschließlich mit einer Kriegsasche als Schadensquelle.",d:3},
  {t:"Besiege einen Gegner aus jeder dieser Gruppen: Ritter, Tier, Untoter, Magier, Riese – ohne zwischendurch zu sterben.",d:2},
  {t:"Besiege Malenia.",d:3},
  {t:"Besiege einen Hauptboss mit exakt 0 verbleibenden roten Fläschchen-Nutzungen im Moment des Sieges.",d:3},
  {t:"Erreiche das Ende des Spiels und besiege den finalen Boss.",d:3}
];
