// HARDCORE-SET: 100 Aufgaben für ein 12-Stunden-Bingo.
// difficulty: 1 = grün / 1 Punkt (hardcore), 2 = orange / 2 Punkte (brutal), 3 = rot / 3 Punkte (extrem).
// Alle Schwierigkeitsstufen sind absichtlich deutlich härter als im ursprünglichen Set.
export const TASKS = [
  {t:"Besiege Margit ohne Geisterasche, NPC-Beschwörung, Schild oder rote Flasche.",d:1},
  {t:"Besiege den Baumwächter in Limgrave zu Fuß, ohne Geisterasche und ohne Fernkampfschaden.",d:1},
  {t:"Besiege den Bluthundritter Darriwil ohne Blaidd, Schild oder rote Flasche.",d:1},
  {t:"Besiege einen Nachtkavalleristen, ohne Torrent zu benutzen und ohne getroffen zu werden, bevor er erstmals vom Pferd fällt.",d:1},
  {t:"Besiege einen Runenbären in freier Wildbahn, ohne Torrent, Geisterasche oder Fernkampfschaden.",d:1},
  {t:"Besiege Godrick ohne Geisterasche/NPC-Summon und benutze im gesamten Kampf höchstens eine rote Flasche.",d:1},
  {t:"Durchquere Schloss Sturmschleier vom Haupttor bis zu Godricks Arena und besiege Godrick, ohne an einer Gnade zu rasten.",d:1},
  {t:"Besiege einen Erdtree Burial Watchdog, ohne einen Treffer zu kassieren.",d:2},
  {t:"Besiege einen Boss ausschließlich mit Guard Counters und kritischen Treffern.",d:1},
  {t:"Besiege einen Boss mit einer unverstärkten +0-Waffe; keine Statusprocs, Geisterasche oder offensive Magie.",d:2},
  {t:"Besiege einen Boss nur mit einer Fackel als Schadensquelle.",d:3},
  {t:"Besiege einen Boss nur mit Bogen/Armbrust; keine Statuspfeile und keine Beschwörungen.",d:1},
  {t:"Besiege einen Boss ausschließlich mit Wurf- und Verbrauchsgegenständen als Schadensquelle.",d:3},
  {t:"Besiege einen Boss ohne Rollen, Springen oder Sprinten während des gesamten Kampfes.",d:3},
  {t:"Besiege einen Boss ohne Lock-on, Schild, Geisterasche und ohne rote Flasche.",d:2},
  {t:"Besiege einen Boss nackt (keine Rüstung), ohne Geisterasche und ohne rote Flasche.",d:2},
  {t:"Besiege einen Boss bei schwerer Ausrüstungslast, ohne Schild oder Geisterasche.",d:2},
  {t:"Besiege einen Boss, während du überladen bist; keine Geisterasche und kein Fernkampfschaden.",d:3},
  {t:"Besiege einen Boss mit maximal 10% LP zu Kampfbeginn und heile während des Kampfes nicht.",d:3},
  {t:"Besiege einen Boss, ohne roten oder blauen Flakon zu benutzen.",d:1},
  {t:"Besiege einen Boss und kassiere während des gesamten Kampfes höchstens einen Treffer.",d:3},
  {t:"Besiege zwei verschiedene Bosse hintereinander, ohne dazwischen an einer Gnade zu rasten oder Fläschchen neu aufzufüllen.",d:1},
  {t:"Besiege drei verschiedene Bosse in einem Leben, ohne dazwischen zu sterben oder an einer Gnade zu rasten.",d:3},
  {t:"Töte einen Boss mit einem Parry/Riposte oder Backstab als finalem Treffer.",d:2},
  {t:"Besiege einen Boss nur mit aufgeladenen schweren Angriffen und kritischen Treffern.",d:1},
  {t:"Besiege einen Boss ausschließlich mit einer Kriegsasche als direkter Schadensquelle.",d:1},
  {t:"Löse in einem einzigen Bossversuch Blutung, Frost und Gift/Scharlachfäule am selben Boss aus und gewinne den Versuch.",d:3},
  {t:"Besiege Rennala ohne Geisterasche, ohne Schild und ohne rote Flasche in Phase 2.",d:1},
  {t:"Durchquere Raya Lucaria vom Haupttor bis Rennala und besiege sie, ohne an einer Gnade zu rasten.",d:1},
  {t:"Besiege den Magmalindwurm Makar ohne Geisterasche, Schild oder Torrent und ohne rote Flasche.",d:1},
  {t:"Besiege den Altus-Plateau-Draconic-Tree-Sentinel ohne Torrent, Geisterasche oder Schild.",d:1},
  {t:"Erreiche Volcano Manor, erledige alle drei normalen Attentatsaufträge und besiege anschließend Rykard.",d:2},
  {t:"Besiege Rykard, ohne die Schlangenjäger-Waffe zu verbessern und ohne Geisterasche.",d:1},
  {t:"Besiege Radahn ohne NPC- oder Spielerbeschwörungen.",d:1},
  {t:"Besiege Radahn ohne NPC-Beschwörungen, Torrent oder rote Flasche.",d:3},
  {t:"Erreiche Nokron und besiege Mimic Tear, nachdem du die Arena mit deiner vollständigen Kampf-Ausrüstung betreten hast; nach dem Betreten nichts um- oder ablegen und keine Geisterasche verwenden.",d:2},
  {t:"Besiege die Valiant Gargoyles ohne Geisterasche und ohne Gift-/Fäule-Käse.",d:3},
  {t:"Besiege einen einzelnen Crucible Knight ohne Geisterasche, Schild oder rote Flasche.",d:1},
  {t:"Besiege Crucible Knight Ordovis und seinen Partner in Auriza Hero's Grave ohne Geisterasche.",d:3},
  {t:"Besiege Elemer of the Briar ohne Geisterasche, Schild oder rote Flasche.",d:3},
  {t:"Besiege den Bell Bearing Hunter in Dragonbarrow/Caelid ohne Geisterasche und ohne Fernkampfschaden.",d:3},
  {t:"Besiege den Putrid Avatar in Dragonbarrow ohne Torrent, Geisterasche oder Fernkampfschaden.",d:3},
  {t:"Besiege den Black Blade Kindred vor dem Bestial Sanctum ohne Geisterasche oder Fernkampfschaden.",d:3},
  {t:"Besiege den Godskin Apostle im Divine Tower of Caelid ohne Schlaf, Geisterasche oder rote Flasche.",d:3},
  {t:"Besiege den Full-Grown Fallingstar Beast auf Mt. Gelmir ohne Torrent oder Geisterasche.",d:2},
  {t:"Besiege Astel, Naturalborn of the Void ohne Geisterasche und ohne rote Flasche.",d:2},
  {t:"Schließe Rannis Quest bis zum Moonlight Altar ab und aktiviere dort eine Gnade.",d:2},
  {t:"Schließe Fias Quest bis zum Sieg über Lichdragon Fortissax ab.",d:2},
  {t:"Erreiche die Frenzied Flame Proscription unter Leyndell und öffne die versiegelte Tür nackt.",d:2},
  {t:"Erreiche Deeproot Depths über die Valiant Gargoyles und aktiviere dort eine Gnade.",d:1},
  {t:"Aktiviere drei verschiedene Große Runen an ihren jeweiligen Göttlichen Türmen.",d:1},
  {t:"Aktiviere vier verschiedene Große Runen an ihren jeweiligen Göttlichen Türmen.",d:2},
  {t:"Besiege Morgott ohne Melina/Geisterasche, ohne Schild und mit höchstens einer roten Flasche.",d:2},
  {t:"Besiege Morgott ohne Beschwörungen und ohne rote Flasche.",d:3},
  {t:"Besiege den Fire Giant ohne Torrent oder Geisterasche.",d:1},
  {t:"Besiege den Fire Giant ohne Torrent, Geisterasche oder rote Flasche.",d:3},
  {t:"Besiege Commander Niall ohne Geisterasche, Bewitching Branch oder rote Flasche.",d:3},
  {t:"Erreiche das Geweihte Schneefeld und besiege dort einen Death Rite Bird ohne Geisterasche.",d:3},
  {t:"Besiege den Death Rite Bird im Geweihten Schneefeld ohne Heilig-Schaden, Geisterasche oder Fernkampf.",d:3},
  {t:"Erreiche Miquellas Haligbaum und besiege Loretta dort ohne Geisterasche.",d:1},
  {t:"Erreiche Elphael und aktiviere die Gnade 'Gebetsraum' / Prayer Room.",d:2},
  {t:"Besiege Malenia ohne Spieler- oder Geisterbeschwörungen.",d:3},
  {t:"Besiege Malenia ohne Beschwörungen und ohne Schild.",d:3},
  {t:"Besiege Malenia ohne Beschwörungen und benutze insgesamt höchstens 5 rote Flaschen.",d:3},
  {t:"Erreiche Mohgwyn Palace ohne den Consecrated-Snowfield-Teleporter zu benutzen.",d:2},
  {t:"Besiege Mohg, Lord of Blood ohne Geisterasche und ohne Mohg's Shackle.",d:1},
  {t:"Besiege Mohg ohne Geisterasche, Mohg's Shackle oder Purifying Crystal Tear.",d:3},
  {t:"Besiege Godskin Duo ohne Geisterasche und ohne Schlaf.",d:3},
  {t:"Besiege Maliketh ohne Geisterasche.",d:2},
  {t:"Besiege Maliketh ohne Geisterasche, Schild oder rote Flasche.",d:3},
  {t:"Besiege Dragonlord Placidusax ohne Geisterasche.",d:2},
  {t:"Besiege Gideon, Godfrey/Hoarah Loux und Radagon/Elden Beast nacheinander, ohne zwischen diesen Bossen dein Build umzurespeccen.",d:2},
  {t:"Besiege Godfrey/Hoarah Loux ohne Geisterasche und ohne rote Flasche.",d:3},
  {t:"Besiege Radagon und Elden Beast ohne Geisterasche.",d:2},
  {t:"Besiege Radagon und Elden Beast ohne Geisterasche und mit höchstens 4 roten Flaschen für beide Kämpfe zusammen.",d:3},
  {t:"Beende das Spiel und löse ein Ende aus, während du mindestens zwei andere noch unerledigte Enden-Questlinien vorbereitet hast.",d:2},
  {t:"Sammle 12 Heilige Tränen und verbessere deinen roten/blauen Flakon auf mindestens +11.",d:2},
  {t:"Erreiche mindestens 12 Fläschchen-Nutzungen und mindestens +10 Flakonstärke.",d:2},
  {t:"Sammle drei legendäre Talismane.",d:2},
  {t:"Sammle drei legendäre Waffen/Armaments.",d:2},
  {t:"Sammle fünf verschiedene Deathroot und gib sie Gurranq.",d:2},
  {t:"Sammle vier verschiedene Drachenherzen und kaufe mindestens zwei Drachenkommunions-Anrufungen.",d:2},
  {t:"Sammle 100.000 Runen auf einmal, trage sie 15 Minuten lang ohne sie auszugeben und erreiche danach lebend eine Gnade.",d:2},
  {t:"Sammle 250.000 Runen auf einmal und gib sie aus, ohne sie vorher zu verlieren.",d:2},
  {t:"Finde und öffne sechs verschiedene Stonesword-Key-Siegel in mindestens vier Regionen.",d:2},
  {t:"Sammle vier verschiedene Bell Bearings und gib alle vier bei den Twin Maiden Husks ab.",d:2},
  {t:"Sammle mindestens je eine normale Schmiedestein-Stufe 1 bis 8 in deinem Inventar.",d:2},
  {t:"Sammle mindestens je eine Dunkelschmiedestein-Stufe 1 bis 9 in deinem Inventar.",d:2},
  {t:"Bringe eine normale Waffe auf +24 und eine Somber-Waffe auf +9.",d:2},
  {t:"Bringe eine normale Waffe auf +25 und eine Somber-Waffe auf +10.",d:2},
  {t:"Besiege je einen benannten Drachen in Limgrave, Caelid und Liurnia, ohne zwischen den drei Siegen zu sterben.",d:2},
  {t:"Besiege innerhalb von 45 Minuten einen Erdtree Avatar, einen Crucible Knight, einen Night's Cavalry und einen Death/Death Rite Bird; keine Geisterasche.",d:3},
  {t:"Besiege innerhalb von 60 Minuten fünf verschiedene Bossgegner in fünf verschiedenen Regionen, ohne Geisterasche.",d:3},
  {t:"Aktiviere innerhalb von 60 Minuten je eine Gnade in Caelid, Altus Plateau, Mt. Gelmir, Nokron und Leyndell; Startzeit beginnt beim Claim.",d:2},
  {t:"Erreiche in einem Leben ohne Tod nacheinander Caelid, Altus Plateau, Volcano Manor, Leyndell und Mountaintops of the Giants und aktiviere in jeder Region eine neue Gnade.",d:3},
  {t:"Durchquere Lake of Rot von der ersten Gnade bis Grand Cloister, ohne Preserving Boluses zu benutzen oder an einer Gnade zu rasten.",d:3},
  {t:"Durchquere Sellia Crystal Tunnel von der Eingangsgnade bis zum Boss und besiege den Fallingstar Beast, ohne zu rasten oder zu sterben.",d:2},
  {t:"Durchquere Auriza Hero's Grave und besiege den Doppel-Crucible-Knight-Boss, ohne zwischendurch an einer Gnade zu rasten.",d:3},
  {t:"Besiege drei verschiedene Evergaol-Bosse ohne Geisterasche und ohne zwischen den Kämpfen zu sterben.",d:2},
  {t:"Besiege Alecto, Black Knife Ringleader ohne Schild oder rote Flasche.",d:3},
];